version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"

python:
  install:
    - requirements: docs/requirements.txt
  # Install our python package before building the docs
    - method: pip
      path: .

sphinx:
  fail_on_warning: true
formats:
  - pdf

