name: building test for each PR
on: 
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed
jobs:
  build_test:
    runs-on: ubuntu-latest
      
      
    container: ghcr.io/JX278/deepflame-dev
    steps:
     - name: Checkout
       uses: actions/checkout@v3
     - name: Build
       run: |
        
        ./Allwmake
    
      




