name: building test for each PR
on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build_test:
    runs-on: ubuntu-latest
      
      
    container: ghcr.io/jx278/deepflame-dev:latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3
     - name: Build
       run: source /opt/openfoam7/etc/bashrc
        ./Allwmake
       shell: bash
        
    
