name: Build and Validation with CPU inference
on: 
  push:
    branches:
     - master
  pull_request:
    branches:
     - master
jobs:
  build_validation:
    runs-on: [self-hosted, linux, x64, 4060Ti]
    if: github.repository_owner == 'deepmodeling'     
    steps:
     - name: Checkout
       uses: actions/checkout@v3

     - name: build and validation with CPU inference 
       env: 
        OMPI_ALLOW_RUN_AS_ROOT: 1 
        OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1 
        OMPI_MCA_btl_vader_single_copy_mechanism: none
       run: 
        /bin/bash -c " echo $PWD 
        && ls $PWD
        && cp -r /root/actions-runner-dev/data/flare_CH4_SandiaD_4D.tbl examples/dfLowMachFoam/fgm/twoD_SandiaD_flareFGM
        && source ~/miniconda3/etc/profile.d/conda.sh && conda activate libcantera && source /opt/openfoam7/etc/bashrc 
        && . configure.sh --use_pytorch&& source ./bashrc && . install.sh 
        && cd test && ./Allrun && conda deactivate "

     - name: test 
       run: | 
         cd test
         cmake -B build
         cmake --build build 
         cd build 
         ctest --output-on-failure

        
    

        
        
