name: Case Validation
on: 
  push:
    branches:
     - libtorch
  pull_request:
    branches:
     - libtorch
jobs:
  validation:
    runs-on: self-hosted
    if: github.repository_owner == 'deepmodeling'    
    container: 
      image: ubuntu:20.04
    steps:
     - name: Checkout
       uses: actions/checkout@v3
     - name: install dependencies
       env:
        DEBIAN_FRONTEND: noninteractive
       run: |
        apt-get update 
        apt-get install -y sudo wget unzip git software-properties-common make cmake g++ mpich openmpi-bin libopenmpi-dev libscalapack-mpi-dev vim
        sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key | apt-key add -" 
        sudo add-apt-repository http://dl.openfoam.org/ubuntu
        sudo apt-get update
        export DEBIAN_FRONTEND=noninteractive
        apt-get -y install openfoam7 
        wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.11.0%2Bcpu.zip
        unzip libtorch-cxx11-abi-shared-with-deps-1.11.0+cpu.zip -d thirdParty 
        rm libtorch-cxx11-abi-shared-with-deps-1.11.0+cpu.zip 
        git clone https://github.com/deepmodeling/deepflame-dev.git
        cd deepflame-dev      
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        sh Miniconda3-latest-Linux-x86_64.sh -b
        . ~/miniconda3/etc/profile.d/conda.sh
        conda create -n libcantera
        conda activate libcantera
        conda install -c cantera libcantera-devel
 
     - name: build
       env: 
        OMPI_ALLOW_RUN_AS_ROOT: 1 
        OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1 
        OMPI_MCA_btl_vader_single_copy_mechanism: none
       run: 
        /bin/bash -c "source ~/miniconda3/etc/profile.d/conda.sh && conda activate libcantera && source /opt/openfoam7/etc/bashrc && . install.sh"
        
     - name: Allrun and Validation 
       env: 
        OMPI_ALLOW_RUN_AS_ROOT: 1 
        OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1 
        OMPI_MCA_btl_vader_single_copy_mechanism: none       
       run: 
        /bin/bash -c "source ~/miniconda3/etc/profile.d/conda.sh && conda activate libcantera && source /opt/openfoam7/etc/bashrc && source bashrc &&cd test && ./Allrun && cmake -B build && cmake --build build && cd build && ctest"
        


        
        

    






        


        
        

    





