name: build with torch
on: 
  push:
    branches:
     - master
  pull_request:
    branches:
     - master
jobs:
  gpu_build:
    runs-on: self-hosted
    if: github.repository_owner == 'deepmodeling'     
    container: 
      image: ubuntu:20.04
    steps:
     - name: Checkout
       uses: actions/checkout@v3
     - name: install dependencies
       env:
        DEBIAN_FRONTEND: noninteractive
       run: |
        apt-get update 
        apt-get install -y sudo wget unzip git software-properties-common make cmake g++ mpich openmpi-bin libopenmpi-dev libscalapack-mpi-dev vim
        sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key | apt-key add -" 
        sudo add-apt-repository http://dl.openfoam.org/ubuntu
        sudo apt-get update
        export DEBIAN_FRONTEND=noninteractive
        apt-get -y install openfoam7 
        git clone https://github.com/deepmodeling/deepflame-dev.git
        cd deepflame-dev      
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        sh Miniconda3-latest-Linux-x86_64.sh -b
        . ~/miniconda3/etc/profile.d/conda.sh
        conda create -n libcantera python=3.8
        conda activate libcantera
        conda install -c cantera libcantera-devel
        conda install pytorch 
        conda install pybind11
        cd /github/home/miniconda3/envs/libcantera/lib
        ln -s libmkl_rt.so.1 libmkl_rt.so.2
 
     - name: build_notorch
       env: 
        OMPI_ALLOW_RUN_AS_ROOT: 1 
        OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1 
        OMPI_MCA_btl_vader_single_copy_mechanism: none
       run: 
        /bin/bash -c "source ~/miniconda3/etc/profile.d/conda.sh && conda activate libcantera && source /opt/openfoam7/etc/bashrc && . install.sh --use_pytorch"
        
        